doamor/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles, only: [:new, :create, :destroy, :edit, :update]
  get "/profiles/busca" => "profiles#busca", as: :busca_profile
  root "profiles#index"

end

doamor/app/models/profile.rb
class Profile < ActiveRecord::Base
  validates :nome, :idade, :peso, :estado, :cidade, presence: true
  belongs_to :user
end

doamor/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile, dependent: :destroy
end

doamor/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

doamor/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  def index
    @profiles = Profile.all
  end

  def new
    @profile = Profile.new
  end

  def create
    valores = params.require(:profile).permit :nome, :idade, :peso, :estado, :cidade
    @profile = Profile.new valores
    if @profile.save
      flash[:notice] = "Perfil salvo com sucesso"
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    id = params[:id]
    @profile = Profile.find(id)
    render :edit
  end

  def update
    id = params[:id]
    @profile = Profile.find(id)
    valores = params.require(:profile).permit :nome, :idade, :peso, :estado, :cidade
    if @profile.update valores
      flash[:notice] = "Perfil atualizado com sucesso"
      redirect_to root_url
    else
      render :edit
    end
  end

  def destroy
    id = params[:id]
    Profile.destroy id
    redirect_to root_url
  end

  def busca
    @nome = params[:nome]
    @profiles = Profile.where "nome like ?", "%#{@nome}%"
  end
end

doamor/app/helpers/application_helper.rb
module ApplicationHelper
end

doamor/app/helpers/profiles_helper.rb
module ProfilesHelper
end

doamor/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doamor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


</body>
</html>

doamor/app/views/profiles/busca.html.erb
<table class ="table table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Peso(Kg)</th>
      <th>Estado</th>
      <th>Cidade</th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
    <tr>
      <td><%= profile.nome %></td>
      <td><%= profile.idade %></td>
      <td><%= profile.peso %></td>
      <td><%= profile.estado %></td>
      <td><%= profile.cidade %></td>
      </tr>
      <%end%>
</div>
  </tbody>
</table>

<%= link_to "Voltar", root_url %>

doamor/app/views/profiles/edit.html.erb
<%= nav_bar brand: "doamor", brand_link: root_url do %>
  <%= form_tag busca_profile_path, method: :get, class: "navbar-form navbar-right" do %>
  <div class="form-group">
    <%= link_to "Editar Conta", edit_user_registration_path, class: "btn btn-default btn-xs" %>
    <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "btn btn-default btn-xs" %>
    <br>
    <br>
    <%= text_field_tag :nome, @nome, class: "form-control" %>
    <%= button_to "Bucar usuários", nil, class: "btn btn-default" %><br>
  </div>
  <% end %>
<% end %>
<div class="container">
<% @profile.errors.full_messages.each do |message| %>
  <div class="alert alert-danger" role="alert"><%= message %></div>
<% end %>
  <%= form_for Profile.new do |f| %>
    <div class="form-group">
      <%= f.label :nome %>
      <%= f.text_field :nome, class: "form-control" %>
    </div>

    <div class="form-inline">
      <div class="form-group">
        <%= f.label :idade %>
        <%= f.number_field :idade, step: 1, class: "form-control"  %>
      </div>

      <div class="form-group">
        <%= f.label :peso %>
        <%= f.number_field :peso, class: "form-control" %>
      </div>
    </div>
    <br>
    <div class="form-inline">
      <div class="form-group">
        <%= f.label :estado %>
        <%= f.text_field :estado, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :cidade %>
        <%= f.text_field :cidade, class: "form-control"  %>
      </div>
    </div>
    <br>
    <%= f.submit "Atualizar o perfil", class:"btn btn-primary"%>
  <% end %>
</div>

doamor/app/views/profiles/index.html.erb
<%= nav_bar brand: "doamor", brand_link: root_url do %>
  <%= form_tag busca_profile_path, method: :get, class: "navbar-form navbar-right" do %>
  <div class="form-group">
    <%= link_to "Editar Conta", edit_user_registration_path, class: "btn btn-default btn-xs" %>
    <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "btn btn-default btn-xs" %>
    <br>
    <br>
    <%= text_field_tag :nome, @nome, class: "form-control" %>
    <%= button_to "Bucar usuários", nil, class: "btn btn-default" %><br>
  </div>
  <% end %>
<% end %>
<div class="container">
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<%end%>
<table class ="table table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Peso(Kg)</th>
      <th>Estado</th>
      <th>Cidade</th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
    <tr>
      <td><%= profile.nome %></td>
      <td><%= profile.idade %></td>
      <td><%= profile.peso %></td>
      <td><%= profile.estado %></td>
      <td><%= profile.cidade %></td>
      <td>
        <div class="form-inline">
          <div class="form-group">
          <%= button_to "Excluir Perfil", profile, method: :delete, class: "btn btn-danger", data: {confirm: "Tem certeza que deseja remover #{profile.nome}?"}%>
          <br>
          <%= link_to "Editar Perfil", edit_profile_path(profile), class: "btn btn-default" %>
          </div>
        </div>
      </td>
      </tr>
      <%end%>
</div>
  </tbody>
</table>
<%= link_to "Criar Perfil", new_profile_path, class: "btn btn-default" %>
</div>

doamor/app/views/profiles/new.html.erb
<%= nav_bar brand: "doamor", brand_link: root_url do %>
  <%= form_tag busca_profile_path, method: :get, class: "navbar-form navbar-right" do %>
  <div class="form-group">
    <%= link_to "Editar Conta", edit_user_registration_path, class: "btn btn-default btn-xs" %>
    <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "btn btn-default btn-xs" %>
    <br>
    <br>
    <%= text_field_tag :nome, @nome, class: "form-control" %>
    <%= button_to "Bucar usuários", nil, class: "btn btn-default" %><br>
  </div>
  <% end %>
<% end %>
<div class="container">
<% @profile.errors.full_messages.each do |message| %>
  <div class="alert alert-danger" role="alert"><%= message %></div>
<% end %>
  <%= form_for Profile.new do |f| %>
    <div class="form-group">
      <%= f.label :nome %>
      <%= f.text_field :nome, class: "form-control" %>
    </div>

    <div class="form-inline">
      <div class="form-group">
        <%= f.label :idade %>
        <%= f.number_field :idade, step: 1, class: "form-control"  %>
      </div>

      <div class="form-group">
        <%= f.label :peso %>
        <%= f.number_field :peso, class: "form-control" %>
      </div>
    </div>
    <br>
    <div class="form-inline">
      <div class="form-group">
        <%= f.label :estado %>
        <%= f.text_field :estado, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :cidade %>
        <%= f.text_field :cidade, class: "form-control"  %>
      </div>
    </div>
    <br>
    <%= f.submit "Criar Perfil", class:"btn btn-primary"%>
  <% end %>
</div>